- name: copy Elastic YUM Repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install Filebeat
  ansible.builtin.yum:
    name: filebeat
    state: Installed